package terminal

const (
	CarriageReturn = "\r"
	LineFeed       = "\n"
	CRLF           = CarriageReturn + LineFeed
	EscapeRune     = '\x1b'
	Escape         = "\x1b"
)

const (
	SyncBegin            = Escape + "[?2026h"
	SyncEnd              = Escape + "[?2026l"
	PasteEnable          = Escape + "[?2004h"
	PasteDisable         = Escape + "[?2004l"
	PasteStart           = Escape + "[200~"
	PasteEnd             = Escape + "[201~"
	KeyboardEnhancePush  = Escape + "[>1u"
	KeyboardEnhancePop   = Escape + "[<u"
	CursorHide           = Escape + "[?25l"
	CursorShow           = Escape + "[?25h"
	ClearLine            = Escape + "[2K"
	ClearScreen          = Escape + "[2J"
	MoveToTop            = Escape + "[H"
	MoveToPosition       = Escape + "[%d;%dH"
	AutoWrapDisable      = Escape + "[?7l"
	AutoWrapEnable       = Escape + "[?7h"
	MoveUpLines          = Escape + "[%dA"
	MoveDownLines        = Escape + "[%dB"
	SGRFormat            = Escape + "[%sm"
	SGRReset             = Escape + "[0m"
	SGRReverse           = Escape + "[7m"
	SGRReverseOff        = Escape + "[27m"
	SGRItalic            = Escape + "[3m"
	SGRItalicOff         = Escape + "[23m"
	SGRBold              = Escape + "[1m"
	SGRBoldOff           = Escape + "[22m"
	BackgroundColorQuery = Escape + "]11;?" + Escape + "\\"
)

const (
	KeyEscapeCSIu            = Escape + "[27u"
	KeyCtrlEscapeCSIu        = Escape + "[27;5u"
	KeyCtrlEscapeModifyOther = Escape + "[27;5;27~"
	KeyShiftEnterCSIu        = Escape + "[13;2u"
	KeyShiftEnterModifyOther = Escape + "[27;2;13~"
	KeyCtrlACSIu             = Escape + "[97;5u"
	KeyCtrlAModifyOther      = Escape + "[27;5;97~"
	KeyCtrlBCSIu             = Escape + "[98;5u"
	KeyCtrlBModifyOther      = Escape + "[27;5;98~"
	KeyCtrlCCSIu             = Escape + "[99;5u"
	KeyCtrlCModifyOther      = Escape + "[27;5;99~"
	KeyCtrlDCSIu             = Escape + "[100;5u"
	KeyCtrlDModifyOther      = Escape + "[27;5;100~"
	KeyCtrlECSIu             = Escape + "[101;5u"
	KeyCtrlEModifyOther      = Escape + "[27;5;101~"
	KeyCtrlFCSIu             = Escape + "[102;5u"
	KeyCtrlFModifyOther      = Escape + "[27;5;102~"
	KeyCtrlKCSIu             = Escape + "[107;5u"
	KeyCtrlKModifyOther      = Escape + "[27;5;107~"
	KeyCtrlOCSIu             = Escape + "[111;5u"
	KeyCtrlOModifyOther      = Escape + "[27;5;111~"
	KeyCtrlUCSIu             = Escape + "[117;5u"
	KeyCtrlUModifyOther      = Escape + "[27;5;117~"
	KeyCtrlWCSIu             = Escape + "[119;5u"
	KeyCtrlWModifyOther      = Escape + "[27;5;119~"
	SequenceArrowUp          = Escape + "[A"
	SequenceArrowDown        = Escape + "[B"
	SequenceArrowRight       = Escape + "[C"
	SequenceArrowLeft        = Escape + "[D"
	SequenceHome             = Escape + "[H"
	SequenceHomeTilde        = Escape + "[1~"
	SequenceHomeSS3          = Escape + "OH"
	SequenceEnd              = Escape + "[F"
	SequenceEndTilde         = Escape + "[4~"
	SequenceEndSS3           = Escape + "OF"
	SequenceDelete           = Escape + "[3~"
	SequencePageUp           = Escape + "[5~"
	SequencePageDown         = Escape + "[6~"
)
